In [1]:
from Bython.Structure import Loadstruc, FetchPDB

#Download 4DJH from RCSB to current working directory
f_pdb = FetchPDB(pdbid='4DJH')

#Load 4DJH in Bython
mypdb = Loadstruc(intype='pdb', filename='4DJH.pdb', hetatm = True, verbose=True)

Number of molecules in input file:  34 

Molid: 1 Molecule_Type: Protein
Chain break encountered in molecule 1 at residue positions: 
261 301 347 

Molid: 2 Molecule_Type: Protein
Chain break encountered in molecule 2 at residue positions: 
261 300 347 

Molid: 3 Molecule_Type: Ligand
Molid: 4 Molecule_Type: Ligand
Molid: 5 Molecule_Type: Ligand
Molid: 6 Molecule_Type: Ligand
Molid: 7 Molecule_Type: Ligand
Molid: 8 Molecule_Type: Ligand
Molid: 9 Molecule_Type: Ligand
Molid: 10 Molecule_Type: Ligand
Molid: 11 Molecule_Type: Ligand
Molid: 12 Molecule_Type: Ligand
Molid: 13 Molecule_Type: Ligand
Molid: 14 Molecule_Type: Ligand
Molid: 15 Molecule_Type: Ligand
Molid: 16 Molecule_Type: Ligand
Molid: 17 Molecule_Type: Ligand
Molid: 18 Molecule_Type: Ligand
Molid: 19 Molecule_Type: Ligand
Molid: 20 Molecule_Type: Ligand
Molid: 21 Molecule_Type: Ligand
Molid: 22 Molecule_Type: Ligand
Molid: 23 Molecule_Type: Ligand
Molid: 24 Molecule_Type: Ligand
Molid: 25 Molecule_Type: Ligand
Molid: 26 Molecu

In [2]:
#mypdb is a dictionary of Bython objects (in this case 34 objects) with keys set to Molid
print len(mypdb), mypdb[1]

34 <Bython.Structure.protein.Protein object at 0x7f1e1d044550>


In [3]:
#Check the molecule tupe of an object
print mypdb[1].molecule_type(), mypdb[20].molecule_type()

Protein Ligand


In [4]:
#Basic Molecule attributes: number of residues (nor), residue ids: resids, atom indices: atmidx, and residue info: residue
print mypdb[1].nor, mypdb[1].resids

447 [55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 263, 

In [5]:
print mypdb[3].nor, mypdb[3].resids

1 [1300]


In [6]:
#Get all information about a residue
print mypdb[3].residue[1300]

{'name': 'JDC', 'chain': 'A', 'atoms': {6933: {'cord': [3.212, -20.41, 59.668], 'B': 48.87, 'name': 'C1', 'O': 1.0}, 6934: {'cord': [2.925, -21.788, 59.558], 'B': 62.55, 'name': 'N2', 'O': 1.0}, 6935: {'cord': [2.2, -22.081, 58.366], 'B': 59.43, 'name': 'C3', 'O': 1.0}, 6936: {'cord': [0.834, -21.417, 58.395], 'B': 43.96, 'name': 'C4', 'O': 1.0}, 6937: {'cord': [0.941, -19.983, 58.845], 'B': 53.74, 'name': 'C4A', 'O': 1.0}, 6938: {'cord': [-0.162, -19.056, 58.639], 'B': 58.61, 'name': 'C5', 'O': 1.0}, 6939: {'cord': [-0.05, -17.705, 59.061], 'B': 64.53, 'name': 'C6', 'O': 1.0}, 6940: {'cord': [1.111, -17.258, 59.67], 'B': 65.23, 'name': 'C7', 'O': 1.0}, 6941: {'cord': [1.231, -15.978, 60.074], 'B': 69.41, 'name': 'O7', 'O': 1.0}, 6942: {'cord': [2.166, -18.147, 59.863], 'B': 64.82, 'name': 'C8', 'O': 1.0}, 6943: {'cord': [2.05, -19.54, 59.431], 'B': 48.05, 'name': 'C8A', 'O': 1.0}, 6944: {'cord': [2.111, -23.598, 58.19], 'B': 61.98, 'name': 'C1A', 'O': 1.0}, 6945: {'cord': [1.727, -24.

In [8]:
print mypdb[1].residue[55]['name']

SER


In [9]:
#Get coordinates of all atoms for residue 55 in protein
print mypdb[1].GetCord(resid=55)

[[-11.855 -43.861  67.808]
 [-11.937 -45.085  67.015]
 [-10.552 -45.525  66.543]
 [ -9.697 -44.684  66.272]
 [-12.847 -44.873  65.804]
 [-12.873 -46.029  64.983]]


In [10]:
#List all atoms indices for residue 55
print mypdb[1].residue[55]['atoms'].keys()

[1, 2, 3, 4, 5, 6]


In [11]:
#Get cordinate for 4th atom in residue 55
print mypdb[1].GetCordbyIdx(atmidx=4)

[ -9.697 -44.684  66.272]


In [12]:
#Get the distance between atoms 2 and 4
print mypdb[1].GetDist(2,4)

2.39383583397


In [13]:
#Get the angle between atoms 2, 3, and 4 in degrees
print mypdb[1].GetAngle(2,3,4)

120.095847681


In [14]:
#Get the dihedral angle between atoms 2, 3, 4, and 5 in degrees
print mypdb[1].GetDihed(2,3,4,5)

-38.9012780383


In [17]:
#Get a subset of a molecule according to a given criteria...say all sidechain atoms for a protein
obj_sc= mypdb[1].GetSubset('sidechain')

print mypdb[1].residue[55]['atoms'].keys()
print obj_sc.residue[55]['atoms'].keys()

[1, 2, 3, 4, 5, 6]
[5, 6]


In [20]:
#Get geometric center of all sidechain atoms
print obj_sc.GetCenter(cen_type='geom')

#Get center of mass of all sidechain atoms
print obj_sc.GetCenter(cen_type='mass')

#Get center of all sidechain atoms using custom weights
import numpy as np
no_of_atoms = len(obj_sc.atmidx)
print obj_sc.GetCenter(cen_type='custom', custom_weight=np.ones(no_of_atoms))

[ -7.20733511 -18.21769149  31.84028664]
[ -7.19294943 -18.23048858  31.84133868]
[ -7.20733511 -18.21769149  31.84028664]


In [21]:
#Let's try to get a subset of backbone atoms in Ligand object
lig_sub= mypdb[3].GetSubset('backbone')

SystemExit: *** PROTEIN SPECIFIC CRITERIA (backbone) SPECIFIED for molecule type Ligand***
 No Subset returned.

To exit: use 'exit', 'quit', or Ctrl-D.


In [23]:
#Get a subset of polar atoms in Ligand object
lig_sub= mypdb[3].GetSubset('polar')
print lig_sub.residue[1300]['atoms']

{6934: {'cord': [2.925, -21.788, 59.558], 'B': 62.55, 'name': 'N2', 'O': 1.0}, 6941: {'cord': [1.231, -15.978, 60.074], 'B': 69.41, 'name': 'O7', 'O': 1.0}, 6945: {'cord': [1.727, -24.318, 59.12], 'B': 64.62, 'name': 'O1', 'O': 1.0}, 6946: {'cord': [2.503, -24.178, 56.921], 'B': 56.3, 'name': 'N2A', 'O': 1.0}, 6952: {'cord': [4.678, -26.293, 57.835], 'B': 55.76, 'name': 'N11', 'O': 1.0}, 6963: {'cord': [6.021, -27.774, 65.151], 'B': 90.73, 'name': 'O3C', 'O': 1.0}}


In [30]:
#Get mass of all polar atoms in ligand 3
print lig_sub.GetMass()

[ 14.0067  15.9994  15.9994  14.0067  14.0067  15.9994]


In [31]:
#Get min and max values of atom coordinates in the x, y, and z directions
print lig_sub.GetRange()

(array([  1.231, -27.774,  56.921]), array([  6.021, -15.978,  65.151]))


In [32]:
#Get distance matrix between all atoms of an object
from Bython.StrucUtils import OBDistMat

print OBDistMat(lig_sub)

[[  0.           6.07387784   2.83336337   3.58384612   5.1319356
    8.75780001]
 [  6.07387784   0.           8.40902682   8.87690222  11.10379012
   13.7064089 ]
 [  2.83336337   8.40902682   0.           2.33610295   3.77627475
    8.17039369]
 [  3.58384612   8.87690222   2.33610295   0.           3.16847692
    9.64574725]
 [  5.1319356   11.10379012   3.77627475   3.16847692   0.           7.58425118]
 [  8.75780001  13.7064089    8.17039369   9.64574725   7.58425118   0.        ]]
