In [1]:
import torch

num_entries = 5000

db = torch.rand(num_entries) > 0.5
db

tensor([1, 0, 0,  ..., 0, 0, 1], dtype=torch.uint8)

In [2]:
def get_parallel_db(db, remove_index):
    return torch.cat((db[0:remove_index],
                      db[remove_index+1:]))

In [3]:
def get_parallel_dbs(db):
    parallel_dbs = list()
    
    for i in range(len(db)):
        pdb = get_parallel_db(db, i)
        parallel_dbs.append(pdb)
    
    return parallel_dbs

In [4]:
pdbs = get_parallel_dbs(db)

In [5]:
def create_db_and_parallels(num_entries):
    db = torch.rand(num_entries) > 0.5
    pdbs = get_parallel_dbs(db)
    
    return db, pdbs

In [6]:
db, pdbs = create_db_and_parallels(20)

In [7]:
db

tensor([1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0],
       dtype=torch.uint8)

In [8]:
pdbs

[tensor([1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0],
        dtype=torch.uint8),
 tensor([1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0],
        dtype=torch.uint8),
 tensor([1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0],
        dtype=torch.uint8),
 tensor([1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0],
        dtype=torch.uint8),
 tensor([1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0],
        dtype=torch.uint8),
 tensor([1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0],
        dtype=torch.uint8),
 tensor([1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0],
        dtype=torch.uint8),
 tensor([1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0],
        dtype=torch.uint8),
 tensor([1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0],
        dtype=torch.uint8),
 tensor([1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0],
        dtype=torch.uint8),
 tensor([1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,