<a href="https://colab.research.google.com/github/ginttone/summary/blob/master/cos_similarity_tfidfvectorizer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# word to back

씨보우 - 워드투백 - 엔그램

## [Similarity(관계성 확인)](https://wikidocs.net/24603)
```
      바나나  사과  저는  좋아요
문서1   0      1     1     1
문서2   1      0     1     1
문서3   2      0     2     2

```

토크나이저 -> 군집화 -> 분류체계 -> 긍정부정 뽑아냄 : 걸러내는 방법으로 사용


In [19]:
from numpy import dot
from numpy.linalg import norm
import numpy as np
def cos_sim(A, B):
       return dot(A, B)/(norm(A)*norm(B))

In [20]:
doc1= np.array([0 , 1 , 1 , 1])
doc2= np.array([1 , 0 , 1 , 1])
doc3= np.array([2 , 0 , 2 , 2])

In [21]:
cos_sim(doc1, doc2)

0.6666666666666667

In [22]:
cos_sim(doc1, doc3)

0.6666666666666667

In [23]:
cos_sim(doc2, doc3)

1.0000000000000002

# [네이버 API사용](https://developers.naver.com/main/)
```
1. 공공 API
  API공통 가이드
    샘플코드 
      로그인방식 API호출 예 
      비로그인 방식 API호출 예
  서비스 API
    검색
     블로그
      오픈 API이용 신청
        Application
         개요 : Client ID(n5q55BwQT2B4ZSaQuxl6, Client Secret(VnlvNdrwph)
         API설정 : 내게 맞는 key설정
           사용 API(검색)
         Playground(beta): 
           API선택(Search-기본검색)
           API URL(https://openapi.naver.com/v1/search/{serviceid})
           serviceid(*) (blog)
           query(*) (검색어)
           display (검색결과 출력수)
           start (검색시작위치)
           sort(유사도Similarity)
           filter(이미지 링크도 가져올 수 있음)

           API호출 
            API 요청
            API 호출 결과

2. 스크레핑
```

# TfidfVectorizer

TF-IDF(Term Frequency - Inverse Document Frequency)는 정보 검색과 텍스트 마이닝에서 이용하는 가중치로, 여러 문서로 이루어진 문서군이 있을 때 어떤 단어가 특정 문서 내에서 얼마나 중요한 것인지를 나타내는 통계적 수치이다. 문서의 핵심어를 추출하거나, 검색 엔진에서 검색 결과의 순위를 결정하거나, 문서들 사이의 비슷한 정도를 구하는 등의 용도로 사용할 수 있다.

TF(단어 빈도, term frequency)는 특정한 단어가 문서 내에 얼마나 자주 등장하는지를 나타내는 값으로, 이 값이 높을수록 문서에서 중요하다고 생각할 수 있다. 하지만 단어 자체가 문서군 내에서 자주 사용 되는 경우, 이것은 그 단어가 흔하게 등장한다는 것을 의미한다. 이것을 DF(문서 빈도, document frequency)라고 하며, 이 값의 역수를 IDF(역문서 빈도, inverse document frequency)라고 한다. TF-IDF는 TF와 IDF를 곱한 값이다.

[출처]위키백과

In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [25]:
corpus = [
    'you know I want your love',
    'I like you',
    'what should I do ',    
]

In [26]:
tfidf = TfidfVectorizer()
tfidf.fit_transform(corpus).toarray()

array([[0.        , 0.46735098, 0.        , 0.46735098, 0.        ,
        0.46735098, 0.        , 0.35543247, 0.46735098],
       [0.        , 0.        , 0.79596054, 0.        , 0.        ,
        0.        , 0.        , 0.60534851, 0.        ],
       [0.57735027, 0.        , 0.        , 0.        , 0.57735027,
        0.        , 0.57735027, 0.        , 0.        ]])

In [27]:
print(tfidf.vocabulary_)

{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}


## Recommanded with cos similarity

tf-idf로 추천시스템 사용
[kaggel-movies_metadata.csv](https://www.kaggle.com/rounakbanik/the-movies-dataset/version/7?select=movies_metadata.csv)

In [28]:
!ls ./drive/MyDrive/Multi_test_deeplearning/movies_metadata.csv

./drive/MyDrive/Multi_test_deeplearning/movies_metadata.csv


In [29]:
import pandas as pd

In [32]:
df_data = pd.read_csv('./drive/MyDrive/Multi_test_deeplearning/movies_metadata.csv')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [33]:
df_data.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [35]:
data = df_data.head(10000)

In [36]:
data = data.dropna()

In [37]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 158 entries, 9 to 9888
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   adult                  158 non-null    object 
 1   belongs_to_collection  158 non-null    object 
 2   budget                 158 non-null    object 
 3   genres                 158 non-null    object 
 4   homepage               158 non-null    object 
 5   id                     158 non-null    object 
 6   imdb_id                158 non-null    object 
 7   original_language      158 non-null    object 
 8   original_title         158 non-null    object 
 9   overview               158 non-null    object 
 10  popularity             158 non-null    object 
 11  poster_path            158 non-null    object 
 12  production_companies   158 non-null    object 
 13  production_countries   158 non-null    object 
 14  release_date           158 non-null    object 
 15  reven

In [38]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [39]:
tfidf= TfidfVectorizer()

In [40]:
tfidf_matrix = tfidf.fit_transform(data['overview'])

열 = 보케브러리 사이즈 같은 것 확인

In [43]:
tfidf_matrix.shape

(158, 2696)

In [46]:
len(tfidf.vocabulary_)

2696

In [47]:
type(tfidf_matrix)

scipy.sparse.csr.csr_matrix

In [49]:
tfidf_matrix[4].toarray()

array([[0., 0., 0., ..., 0., 0., 0.]])

##  linear_kernel 

두 cos(코사인)의 각도를 자동으로 구해 sim(시밀러리티)비교해줌

In [51]:
from sklearn.metrics.pairwise import linear_kernel

In [54]:
cos_sim = linear_kernel(tfidf_matrix)
type(cos_sim), cos_sim.shape

(numpy.ndarray, (158, 158))

In [55]:
cos_sim[3]

array([0.03403894, 0.07378662, 0.0606532 , 1.        , 0.05231864,
       0.05361942, 0.04305033, 0.01963748, 0.03302958, 0.04013632,
       0.05650286, 0.04380791, 0.045455  , 0.0360105 , 0.07208718,
       0.06037126, 0.02463999, 0.06438099, 0.0261279 , 0.03232211,
       0.03084823, 0.04654037, 0.05100054, 0.02586476, 0.01778496,
       0.05746612, 0.10967293, 0.0282976 , 0.04640804, 0.02406314,
       0.0671682 , 0.03956612, 0.04875229, 0.04437252, 0.02699316,
       0.02809418, 0.04223523, 0.02060186, 0.05070264, 0.03129839,
       0.02382746, 0.03403162, 0.03612028, 0.0502291 , 0.04674237,
       0.07158003, 0.02806686, 0.03066928, 0.07962729, 0.04691775,
       0.00644533, 0.0481169 , 0.03853567, 0.03240614, 0.01586077,
       0.02972285, 0.06138844, 0.02404479, 0.02269754, 0.03191292,
       0.05483523, 0.03238852, 0.10369226, 0.01014625, 0.02365042,
       0.07221074, 0.0937075 , 0.06614349, 0.06212896, 0.03717476,
       0.03104298, 0.04467526, 0.04421634, 0.0348611 , 0.04193

## 특정값(어떠한 글자)을 cos_sim에 넣어 값을 구해보자

In [56]:
indeces= pd.Series(data.index, index=data['title']).drop_duplicates()

In [57]:
indeces.head(5)

title
GoldenEye                                    9
Friday                                      68
From Dusk Till Dawn                         69
Blue in the Face                           153
Mighty Morphin Power Rangers: The Movie    178
dtype: int64

In [58]:
indeces['Friday']

68

In [ ]:
list(cos_sim[68])

```
Friday 68 과 가장 비슷한/근접한 영화 리스트

[0.13194603087080797,
 0.030927327604283728,
 0.0467927108671522,
 0.062128961011914285,
 0.02819879512031219,
 0.022630888578312233,
 0.062094365926947295,
 0.04486089904579155,
 0.030344648750782806,
 ...

 ```

In [ ]:
cosim_list= list(enumerate(cos_sim[68]))
cosim_list # 영화의 index를 구하기 위한 조치

```
[(0, 0.13194603087080797),
 (1, 0.030927327604283728),
 (2, 0.0467927108671522),
 (3, 0.062128961011914285),
 (4, 0.02819879512031219),
 (5, 0.022630888578312233),
 (6, 0.062094365926947295),
 (7, 0.04486089904579155),
 ...
```

sorted(list(cos_sim[68])) 시밀라리티 순서대로 정렬

sorted(list(cos_sim[68]),reverse=True) 시밀라리티가 가장 높은 순으로 정렬-리버스

sorted(cosim_list, key=lambda x:x[1] ,reverse=True)람다는 for문처럼 넣어줌- 1번째에 넣음

In [69]:
cosim_index = sorted(cosim_list, key=lambda x:x[1] ,reverse=True)
cosim_index[1:11] #나 자신 빠지고 상위 10위 안에 드는 것만 가져옴

[(137, 0.2260806869818658),
 (67, 0.20577065758382976),
 (139, 0.18933514188443545),
 (85, 0.1687057669941765),
 (84, 0.14086168813612873),
 (118, 0.13905922820403888),
 (14, 0.1388409776447674),
 (90, 0.13673014182356702),
 (71, 0.13438619076762243),
 (82, 0.1328692152222701)]

영화이름으로 바꾸기(숫자->텍스트)

```
for i in cosim_index:
  i[0]
```


In [71]:
[i[0] for i in cosim_index[1:11]]

[137, 67, 139, 85, 84, 118, 14, 90, 71, 82]

In [73]:
movie_indeces = [i[0] for i in cosim_index[1:11]]

In [76]:
data['title'].iloc[movie_indeces]

7329                You Only Live Twice
2832              From Russia with Love
7333              Never Say Never Again
3517        The Man with the Golden Gun
3516                          Moonraker
5734                    Die Another Day
638                 Mission: Impossible
3859               Diamonds Are Forever
2875                   Live and Let Die
3511    On Her Majesty's Secret Service
Name: title, dtype: object



```
      doc1   doc2   doc3
doc1  1.0    0232   0.323
doc2  0.323  1.0    0.323
doc3  0.32   0.123  1.0
```