# Python Practical Exam

© Explore Data Science Academy 
## Instructions to students
* **DO NOT ADD / REMOVE CELLS FROM THIS NOTEBOOK, AND DO NOT CHANGE THE NAMES OF THE FUNCTIONS REQUIRED FOR TESTING.**
  
* This exam consists of six questions. Each of the questions is independent and do not require you to use functions built from previous questions. You can answer the questions in any order you like.

* Ensure that the answers to your questions do not contain `syntax` or `indentation` errors. Questions with these errors will break the auto grader and will mark the _**entire exam**_ as incorrect. The auto grader will give you an error message if this is the case. Use this error message to correct the offending code or comment it out before resubmitting.
* You will be able to make _**multiple submissions**_ to the auto grader. Use this ability to check if a question you have answered is correct before proceeding to the next question.
* Only place code in sections that contain the `# Your code here.` comment.
* We have provided some expected outputs for your code. Use these to determine if your code behaves as intended.
* Some questions may have multiple requirements. It is possible to receive partial marks in these questions, so if you get stuck, try to submit to the auto grader before moving on.

In [16]:
import numpy as np
import pandas as pd

## Section 1: Numerical computation
### Question 1
We have a rope and want to cut the rope into four pieces to make a square. Given a rope of length $x$, what is the largest square (by area) that can be built given that a side of the square, $s$, can only be integer values? Units of measurement can be ignored. We are only interested in the numerical value of the solution.
<p align="center">
<img src="https://raw.githubusercontent.com/Explore-AI/Pictures/master/python_fundamentals/python_exam/Largest_Square_Rope.jpg"
     alt="Largest Square"
     style="float: center; padding-bottom=0.5em"
     width=700px/>
     <br>
     <em>Figure 1: Area of the largest square enclosed by a rope. </em>
</p>    

**Function specifications**

*Argument(s):*

- **x** `(float)` $\rightarrow$ the length of the rope.

*Return:* 

- **area** `(int)` $\rightarrow$ the area of the square formed by the rope.

> 💡**HINT**💡
>
>The perimeter of the square cannot exceed the length of the rope.

In [17]:
### START FUNCTION
def largest_square(x):
    # Your code here.
    s= int(x/4)
    return s**2
### END FUNCTION

In [12]:
largest_square(12)

9

_**Expected outputs:**_
```python
largest_square(12) == 9
largest_square(41.5) == 100
largest_square(324) == 6561
```

### Question 2
Given a square matrix of size $n\times n $ that only contains integers, compute the sum of the two diagonals. If the dimension of the square matrix is odd, make sure that you are not double-counting the value at the centre of the matrix.

<p align="center">
<img src="https://raw.githubusercontent.com/Explore-AI/Pictures/master/python_fundamentals/python_exam/Sum_of_diagonals.jpg"
     alt="Sum of diagonals"
     style="float: center; padding-bottom=0.5em"
     width=50%/>
     <br>
     <em>Figure 2: Sum of diagonals.</em>
</p>    


**Function specifications**

*Arguments:*
- **matrix** `(numpy.ndarray)` $\rightarrow$ input matrix to be used for computing the sum.

*Return:*
- **sum** `(int)` $\rightarrow$  return the sum of the two diagonals.


In [18]:
### START FUNCTION
def sum_of_diagonals(matrix):
    # Your code here.
    n = len(matrix)
    primary = 0
    secondary = 0;
    for i in range(0, n):
        primary += matrix[i][i]
        secondary += matrix[i][n-i-1]
    if (n % 2 == 0): return primary + secondary
    else: return primary + secondary - matrix[n//2][n//2]
    #return 
### END FUNCTION

In [19]:
matrix =np.random.randint(10,size=(4,4))
print(matrix)
sum_of_diagonals(matrix)

[[1 8 1 3]
 [2 9 9 0]
 [5 9 5 0]
 [4 4 5 0]]


40

_**Expected outputs:**_
```python
matrix = np.array([[7, 0, 8],
                   [6, 9, 1],
                   [3, 8, 4]])
sum_of_diagonals(matrix)==31


matrix = np.array([[4, 1, 1, 1],
                   [1, 3, 8, 0],
                   [0, 8, 5, 7],
                   [1, 6, 1, 3]])
sum_of_diagonals(matrix)==33
```

## Section 2: Strings and lists

### Question 3:

Write a function that computes the ratio of vowels vs. consonants ($\frac{vowels}{consonants}$) in a given sentence. The ratio should be given as a floating-point number rounded off to two decimal places. When writing your function, be sure to appropriately cater for the following punctuation marks:
- apostrophes (')
- quotations (")
- full stops (.)
- commas (,)
- exclamations (!)  
- question marks (?)
- colons (:)
- semicolons (;)

*Arguments:*
- **sentence** `(string)` $\rightarrow$ sentence required to compute the ratio.

*Return:*
- **ratio** `(float)` $\rightarrow$ a ratio that describes the number of vowels to consonants: vowels/consonants.

> 💡**HINT**💡
>
>Remember to cater for the white spaces that appear in your sentence.

In [20]:
### START FUNCTION
def vowel_consonant_ratio(sentence):
    # Your code here.
    vowels=0
    consonants=0
    specials=0
    for i in sentence:
        if(i == 'a'or i == 'e'or i == 'i'or i == 'o'or i == 'u' or
           i == 'A'or i == 'E'or i == 'I'or i == 'O'or i == 'U' ):
               vowels=vowels+1;
        elif(i=="'" or i=='"' or i=='!'or i==','or i=='.'or i=='?'or i==':'or i==';' or i==' '):
            specials=specials+1;
        else:
            consonants=consonants+1;    
    ratio=vowels/consonants
    ratio = round(ratio, 2)
    return ratio
### END FUNCTION

In [21]:
vowel_consonant_ratio("Thomas! Where have you been?")

0.83

***Expected outputs***

```python
vowel_consonant_ratio("This is a random sentence!")==0.62
vowel_consonant_ratio("Thomas! Where have you been?")==0.83
```

### Question 4

Write a function that will redact every third word in a sentence. Make use of the hashtag (`#`) symbol to redact the characters that make up the word, i.e. if the word is five characters long then a string of five hashtags should replace that word. However, this should not redact any of the following punctuation marks:
- apostrophes (')
- quotations (")
- full stops (.)
- commas (,)
- exclamations (!)  
- question marks (?)
- colons (:)
- semicolons (;)

*Arguments:*
- **sentence** `(string)` $\rightarrow$ sentence that needs to be redacted.

*Return:*
- **redacted sentence** `(string)`$\rightarrow$ every third word should be redacted.

In [22]:
### START FUNCTION
def redact_words(sentence):
    # Your code here.
    sentence=sentence.split()    
    length=len(sentence)
    letters=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
    for i in range (2, length, 3):
        for letter in sentence[i]:
            if letter.lower() in letters:                
                sentence[i]=sentence[i].replace(letter,"#")  
    redacted_sentence=" ".join(str(x) for x in sentence)
    return redacted_sentence
### END FUNCTION   

In [23]:
sentence = "My dear Explorer, do you understand the nature of the given question?"
redact_words(sentence)

'My dear ########, do you ########## the nature ## the given ########?'

***Expected outputs***

```python
sentence = "My dear Explorer, do you understand the nature of the given question?"
redact_words(sentence) ==  'My dear ########, do you ########## the nature ## the given ########?'

sentence = "Explorer, this is why you shouldn't come to a test unprepared."
redact_words(sentence)=="Explorer, this ## why you #######'# come to # test unprepared."

```

### Question 5

Given an alphanumeric list, separate it into three different lists stored in a dictionary:

- The first list should only contain lowercase letters.
- The second list should only contain uppercase letters.
- The third list should only contain numbers.

Each list stored in the dictionary should be stored in ascending order. Use the following naming convention when creating your lists:
- numbers
- uppercase
- lowercase

Make sure that you adhere to the above instruction, as the name of your lists will be used to mark your function.

*Arguments:*
- **character_list:** `(list)` $\rightarrow$ list of alphanumeric characters.

*Return:*
- **dictionary** `(dict)` $\rightarrow$  dictionary containing all three lists.

In [69]:
### START FUNCTION
def create_dictionary(character_list):
    # Your code here.
    letters=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
    lettersu=['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
    num_list=[x for x in character_list if x not in letters and x not in lettersu]
    num_list=sorted(num_list)
    uppercase_list=[x for x in character_list if x in lettersu]
    uppercase_list=sorted(uppercase_list)
    lowercase_list=[x for x in character_list if x in letters]
    lowercase_list=sorted(lowercase_list)
    keys=['numbers', 'uppercase', 'lowercase']
    values=[num_list, uppercase_list, lowercase_list]
    dictionary=dict(zip(keys, values))
    return dictionary
### END FUNCTION

In [70]:
lst = [2,'j','K','o',6,'x',5,'A',3.2]
create_dictionary(lst)

{'numbers': [2, 3.2, 5, 6],
 'uppercase': ['A', 'K'],
 'lowercase': ['j', 'o', 'x']}

***Expected outputs***

```python
lst = [2,'j','K','o',6,'x',5,'A',3.2]
create_dictionary(lst)

{'numbers': [2, 3.2, 5, 6],
 'uppercase': ['A', 'K'],
 'lowercase': ['j', 'o', 'x']}
 ```



## Section 3: DataFrames
You will need the below DataFrames to answer the following questions.

_**DO NOT ALTER THESE DATAFRAMES, AS DOING SO CAN LEAD TO A NEGATIVE MARK.**_



In [89]:
country_map_df = pd.read_csv('https://raw.githubusercontent.com/Explore-AI/Public-Data/master/AnalyseProject/country_code_map.csv', index_col='Country Code')
population_df = pd.read_csv('https://raw.githubusercontent.com/Explore-AI/Public-Data/master/AnalyseProject/world_population.csv', index_col='Country Code')
meta_df = pd.read_csv('https://raw.githubusercontent.com/Explore-AI/Public-Data/master/AnalyseProject/metadata.csv', index_col='Country Code')
country_map_df.head()

Country Name
Country Code             
ABW                 Aruba
AFG           Afghanistan
AGO                Angola
ALB               Albania
AND               Andorra

_**DataFrame specifications:**_

The DataFrames provide information about the population of the world for various years. Some things to note:
* All DataFrames have a `Country Code` as an index, which is a three-letter code referring to a country.
* The `country_map_df` data maps the `Country Code` to a `Country Name`.
* The `population_df` data contains information on the population for a given country between the years 1960 and 2017.
* The `meta_df` data contains meta-information about each country, including its geographical region, its income group, and a comment on the country as a whole.

### Question 6

Write a function that will return a list of countries for a specified region and income group. If the specified region and income group do not return a country, return `None` as the value.


**Function specifications**

*Argument(s):*
- **region** `(string)` $\rightarrow$ the region you want to query.
- **income_group** `(string)` $\rightarrow$ the income group you want to query.


*Return:*
- **countries** `(list)` $\rightarrow$ return a list of countries that match the search criteria or **`None`** if no countries are found.

In [99]:
### START FUNCTION
def find_countries_by_region_and_income(region,income_group):
    # Your code here.
    custom_df=meta_df[(meta_df['Region']== region) & (meta_df["Income Group"]== income_group)]
    countries_abb = custom_df.index.tolist()
    if len(countries_abb)== 0:
        countries = None
    else:
        countries_df=country_map_df[country_map_df.index.isin(countries_abb)]
        countries=countries_df['Country Name'].tolist()
    return countries
### END FUNCTION

In [105]:
countries=find_countries_by_region_and_income('Sub-Saharan Africa','Upper middle income')
countries

['Botswana',
 'Gabon',
 'Equatorial Guinea',
 'Mauritius',
 'Namibia',
 'South Africa']

***Expected output***

```python
find_countries_by_region_and_income('South Asia','High income')==None
find_countries_by_region_and_income('Europe & Central Asia','Low income')==['Tajikistan']
find_countries_by_region_and_income('Sub-Saharan Africa','Upper middle income')==['Botswana','Gabon','Equatorial Guinea','Mauritius','Namibia','South Africa']
```